
package org.jco.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param factura
     * @param tokenPassword
     * @param tokenEmpresa
     * @param adjuntos
     * @return
     *     returns org.jco.jaxws.client.DocumentResponse
     */
    @WebMethod(operationName = "Enviar", action = "http://tempuri.org/IService/Enviar")
    @WebResult(name = "EnviarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Enviar", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.Enviar")
    @ResponseWrapper(localName = "EnviarResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.EnviarResponse")
    public DocumentResponse enviar(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "factura", targetNamespace = "http://tempuri.org/")
        FacturaGeneral factura,
        @WebParam(name = "adjuntos", targetNamespace = "http://tempuri.org/")
        String adjuntos);

    /**
     * 
     * @param tokenPassword
     * @param tokenEmpresa
     * @param documento
     * @return
     *     returns org.jco.jaxws.client.DocumentStatusResponse
     */
    @WebMethod(operationName = "EstadoDocumento", action = "http://tempuri.org/IService/EstadoDocumento")
    @WebResult(name = "EstadoDocumentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EstadoDocumento", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.EstadoDocumento")
    @ResponseWrapper(localName = "EstadoDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.EstadoDocumentoResponse")
    public DocumentStatusResponse estadoDocumento(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "documento", targetNamespace = "http://tempuri.org/")
        String documento);

    /**
     * 
     * @param tokenPassword
     * @param correo
     * @param tokenEmpresa
     * @param documento
     * @param adjuntos
     * @return
     *     returns org.jco.jaxws.client.SendEmailResponse
     */
    @WebMethod(operationName = "EnvioCorreo", action = "http://tempuri.org/IService/EnvioCorreo")
    @WebResult(name = "EnvioCorreoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnvioCorreo", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.EnvioCorreo")
    @ResponseWrapper(localName = "EnvioCorreoResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.EnvioCorreoResponse")
    public SendEmailResponse envioCorreo(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "documento", targetNamespace = "http://tempuri.org/")
        String documento,
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo,
        @WebParam(name = "adjuntos", targetNamespace = "http://tempuri.org/")
        String adjuntos);

    /**
     * 
     * @param tokenPassword
     * @param tokenEmpresa
     * @param documento
     * @return
     *     returns org.jco.jaxws.client.DownloadPDFResponse
     */
    @WebMethod(operationName = "DescargaPDF", action = "http://tempuri.org/IService/DescargaPDF")
    @WebResult(name = "DescargaPDFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DescargaPDF", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.DescargaPDF")
    @ResponseWrapper(localName = "DescargaPDFResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.DescargaPDFResponse")
    public DownloadPDFResponse descargaPDF(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "documento", targetNamespace = "http://tempuri.org/")
        String documento);

    /**
     * 
     * @param tokenPassword
     * @param tokenEmpresa
     * @param documento
     * @return
     *     returns org.jco.jaxws.client.DownloadXMLResponse
     */
    @WebMethod(operationName = "DescargaXML", action = "http://tempuri.org/IService/DescargaXML")
    @WebResult(name = "DescargaXMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DescargaXML", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.DescargaXML")
    @ResponseWrapper(localName = "DescargaXMLResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.DescargaXMLResponse")
    public DownloadXMLResponse descargaXML(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "documento", targetNamespace = "http://tempuri.org/")
        String documento);

    /**
     * 
     * @param tokenPassword
     * @param tokenEmpresa
     * @return
     *     returns org.jco.jaxws.client.FoliosRemainingResponse
     */
    @WebMethod(operationName = "FoliosRestantes", action = "http://tempuri.org/IService/FoliosRestantes")
    @WebResult(name = "FoliosRestantesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FoliosRestantes", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.FoliosRestantes")
    @ResponseWrapper(localName = "FoliosRestantesResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.FoliosRestantesResponse")
    public FoliosRemainingResponse foliosRestantes(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword);

    /**
     * 
     * @param password
     * @param tokenPassword
     * @param tokenEmpresa
     * @param certificado
     * @return
     *     returns org.jco.jaxws.client.LoadCertificateResponse
     */
    @WebMethod(operationName = "CargarCertificado", action = "http://tempuri.org/IService/CargarCertificado")
    @WebResult(name = "CargarCertificadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargarCertificado", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.CargarCertificado")
    @ResponseWrapper(localName = "CargarCertificadoResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.CargarCertificadoResponse")
    public LoadCertificateResponse cargarCertificado(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "certificado", targetNamespace = "http://tempuri.org/")
        String certificado,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param tokenPassword
     * @param datosEvento
     * @param tokenEmpresa
     * @return
     *     returns org.jco.jaxws.client.EventoResponse
     */
    @WebMethod(operationName = "GenerarEvento", action = "http://tempuri.org/IService/GenerarEvento")
    @WebResult(name = "GenerarEventoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerarEvento", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.GenerarEvento")
    @ResponseWrapper(localName = "GenerarEventoResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.GenerarEventoResponse")
    public EventoResponse generarEvento(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "datosEvento", targetNamespace = "http://tempuri.org/")
        DatosEvento datosEvento);

    /**
     * 
     * @param tokenPassword
     * @param tokenEmpresa
     * @param documento
     * @param documentoEvento
     * @return
     *     returns org.jco.jaxws.client.DescargarEventoResponse
     */
    @WebMethod(operationName = "DescargarEventoXML", action = "http://tempuri.org/IService/DescargarEventoXML")
    @WebResult(name = "DescargarEventoXMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DescargarEventoXML", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.DescargarEventoXML")
    @ResponseWrapper(localName = "DescargarEventoXMLResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.DescargarEventoXMLResponse")
    public DescargarEventoResponse descargarEventoXML(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "documentoEvento", targetNamespace = "http://tempuri.org/")
        String documentoEvento,
        @WebParam(name = "documento", targetNamespace = "http://tempuri.org/")
        String documento);

    /**
     * 
     * @param tokenPassword
     * @param tokenEmpresa
     * @param documento
     * @return
     *     returns org.jco.jaxws.client.ContenedorResponse
     */
    @WebMethod(operationName = "GenerarContenedor", action = "http://tempuri.org/IService/GenerarContenedor")
    @WebResult(name = "GenerarContenedorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerarContenedor", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.GenerarContenedor")
    @ResponseWrapper(localName = "GenerarContenedorResponse", targetNamespace = "http://tempuri.org/", className = "org.jco.jaxws.client.GenerarContenedorResponse")
    public ContenedorResponse generarContenedor(
        @WebParam(name = "tokenEmpresa", targetNamespace = "http://tempuri.org/")
        String tokenEmpresa,
        @WebParam(name = "tokenPassword", targetNamespace = "http://tempuri.org/")
        String tokenPassword,
        @WebParam(name = "documento", targetNamespace = "http://tempuri.org/")
        String documento);

}
